# ArgoCD Application - deploys the sample app to the staging namespace.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-order-service-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/officialasishkumar/keploy-argocd-demo.git
    targetRevision: main
    path: environments/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
